name: glmark2-wayland
version: '0.1'
summary: GLMark2 on Wayland
description: |
  GLMark2 on Wayland
base: core18
confinement: strict
grade: devel

apps:
  glmark2-wayland:
    command: |
      bash -c "XDG_RUNTIME_DIR=$(dirname $XDG_RUNTIME_DIR) \
               LIBGL_DRIVERS_PATH=$(find $SNAP/usr/lib/ -name dri) \
                 $SNAP/usr/bin/glmark2-wayland"
    plugs:
      - wayland

parts:
  glmark2-wayland:
    plugin: nil
    stage-packages:
      - glmark2-wayland

layout:
  /usr/share/glmark2:
    bind: $SNAP/usr/share/glmark2

